# Generated by Django 4.2.5 on 2023-10-05 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exames', '0003_pedidosexames'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaoexame',
            name='status',
            field=models.CharField(choices=[('E', 'Em análise'), ('F', 'Finalizando')], max_length=2),
        ),
    ]
